version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: SonarAnalyzer.CSharp
    versions:
    - 8.17.0.26580
    - 8.18.0.27296
    - 8.19.0.28253
    - 8.20.0.28934
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: coverlet.msbuild
    versions:
    - 3.0.2
  - dependency-name: Moq
    versions:
    - 4.16.0
  - dependency-name: Newtonsoft.Json
    versions:
    - 12.0.3
